spring:
  sql:
    init:
      mode: never
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME} # todo remove. see example properties
    password: ${DB_PASSWORD} # todo remove
    driverClassName: org.postgresql.Driver

logging:
  level:
    com.homework.conference: DEBUG
    org:
      hibernate: ERROR