spring:
  sql:
    init:
      mode: never
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true

logging:
  level:
    com.homework.conference: DEBUG
    org:
      hibernate: ERROR